apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moviedb-ingress
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: moviedb.fd3aa0ead8b7482883d4.northeurope.aksapp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moviedbclient
                port:
                  number: 80
