# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: moviedbclient
spec:
  type: ClusterIP # Expose externally
  selector:
    app: moviedbclient
  ports:
    - protocol: TCP
      port: 80 # Exposed service port
      targetPort: 80 # Container port inside the frontend container
---
apiVersion: v1
kind: Service
metadata:
  name: moviedbserver
spec:
  type: ClusterIP
  selector:
    app: moviedbserver
  ports:
    - protocol: TCP # The protocol the SERVICE will listen to
      port: 8080 # SERVICE exposed port
      targetPort: 8080 # Container exposed port
